name: express.js deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

  - name: Install SSH key
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.PUB_KEY }}
      name: id_rsa
      known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: git remote
      run: |
        git remote add lolipop ${{ secrets.MC_REP_REMOTE_KEY }}

    - name: deploy
      run: git push lolipop HEAD:master


